from turtle import *

speed(5)

pencolor('black')
fillcolor('black')
begin_fill()

for _ in range(2):
    forward(50)
    right(90)
    forward(100)
    right(90)
end_fill()
teleport(50, 0)
pencolor('yellow')
fillcolor('yellow')
begin_fill()
for _ in range(2):
    forward(50)
    right(90)
    forward(100)
    right(90)
end_fill()
teleport(100, 0)
pencolor('red')
fillcolor('red')
begin_fill()
for _ in range(2):
    forward(50)
    right(90)
    forward(100)
    right(90)
end_fill()
teleport(0, 400)
pencolor('red')
fillcolor('red')
begin_fill()
for _ in range(2):
    forward(150)
    right(90)
    forward(25)
    right(90)
end_fill()
teleport(0, 375)
pencolor('white')
fillcolor('white')
begin_fill()
for _ in range(2):
    forward(150)
    right(90)
    forward(25)
    right(90)
end_fill()
teleport(0, 350)
pencolor('blue')
fillcolor('blue')
begin_fill()
for _ in range(2):
    forward(150)
    right(90)
    forward(25)
    right(90)
end_fill()
done()