from turtle import *

speed(5)

pensize(1)
pencolor('red')
fillcolor('red')
begin_fill()
for _ in range(2):
    forward(360)
    right(90)
    forward(120)
    right(90)
end_fill()
pencolor('blue')
fillcolor('blue')
begin_fill()
for _ in range(2):
    forward(120)
    left(90)
    forward(120)
    left(90)
end_fill()
penup()
forward(120)
pendown()
pencolor('black')
fillcolor('white')
begin_fill()
for _ in range(2):
    forward(240)
    left(90)
    forward(120)
    left(90)
end_fill()
teleport(90, 65)
pencolor('white')
fillcolor('white')
begin_fill()
for _ in range(5):
    right(144)
    forward(60)
end_fill()
backward(23)
begin_fill()
for _ in range(5):
    right(72)
    forward(14.62)
end_fill()
done()